version: "3.8"

x-app-defaults: &app-defaults
  restart: always
  networks:
    - clapeecom
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  vid2vid: #From https://github.com/ai-dock/comfyui
    <<: *app-defaults
    container_name: vid2vid
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    volumes:
      - ./workspace:${WORKSPACE:-/workspace/}
      - ./config/vid2vid/provisioning.sh:/opt/ai-dock/bin/provisioning.sh
      - ./config/vid2vid/models.csv:/opt/ai-dock/bin/models.csv
      - ./config/vid2vid/nodes.csv:/opt/ai-dock/bin/nodes.csv
    ports:
      - ${COMFYUI_PORT_HOST:-8188}:${COMFYUI_PORT:-8188}
    environment:
      - COMFYUI_BRANCH=${COMFYUI_BRANCH:-master}
      - COMFYUI_FLAGS=${COMFYUI_FLAGS:-}
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
      - WORKSPACE=${WORKSPACE:-/workspace}
      - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH}
      - WEB_USER=${WEB_USER}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}
      - NODES_CSV_FILE=${NODES_CSV_FILE:-/opt/ai-dock/bin/nodes.csv}
      - MODELS_CSV_FILE=${MODELS_CSV_FILE:-/opt/ai-dock/bin/models.csv}